version: '3.8'

services:
  user_service:
    build:
      context: ./microservices/user_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=testing
    networks:
      - ecommerce-network

  product_catalog_service:
    build:
      context: ./microservices/product_catalog_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=testing
    networks:
      - ecommerce-network

  shopping_cart_service:
    build:
      context: ./microservices/shopping_cart_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=testing
    networks:
      - ecommerce-network

  order_processing_service:
    build:
      context: ./microservices/order_processing_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=testing
    networks:
      - ecommerce-network

  notification_service:
    build:
      context: ./microservices/notification_service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=testing
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
