name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d
          # Wait for services to be ready
          sleep 30

      - name: Run Unit Tests
        run: |
          pytest tests/test_*_service.py --junitxml=test-reports/unit-results.xml

      - name: Run Integration Tests
        run: |
          pytest tests/test_services.py --junitxml=test-reports/integration-results.xml

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: test-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-reports/

      - name: Tear Down Docker Containers
        if: always()
        run: docker-compose down --volumes --remove-orphans