name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start User Service
        run: |
          nohup python microservices/user_service.py &
      
      - name: Start Product Catalog Service
        run: |
          nohup python microservices/product_catalog_service.py &
      
      - name: Start Shopping Cart Service
        run: |
          nohup python microservices/shopping_cart_service.py &
      
      - name: Start Order Processing Service
        run: |
          nohup python microservices/order_processing_service.py &
      
      - name: Start Notification Service
        run: |
          nohup python microservices/notification_service.py &

      - name: Run Unit and Integration Tests
        run: |
          pytest --junitxml=test-reports/results.xml
        continue-on-error: true

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/results.xml

      - name: Display Pytest Report
        if: failure()
        run: cat test-reports/results.xml

  performance-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Locust tests for each microservice
      - name: Run Locust Test for User Service
        run: |
          locust -f performance_tests/locustfile.py --headless -u 10 -r 2 --host=http://localhost:5001 --run-time 2m

      - name: Run Locust Test for Product Catalog Service
        run: |
          locust -f performance_tests/locustfile.py --headless -u 10 -r 2 --host=http://localhost:5002 --run-time 2m

      - name: Run Locust Test for Shopping Cart Service
        run: |
          locust -f performance_tests/locustfile.py --headless -u 10 -r 2 --host=http://localhost:5003 --run-time 2m

      - name: Run Locust Test for Order Processing Service
        run: |
          locust -f performance_tests/locustfile.py --headless -u 10 -r 2 --host=http://localhost:5004 --run-time 2m

      - name: Run Locust Test for Notification Service
        run: |
          locust -f performance_tests/locustfile.py --headless -u 10 -r 2 --host=http://localhost:5005 --run-time 2m
